name: flutter_outbound
description: ""
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http:
  shared_preferences:
  flutter_secure_storage:
  provider:
  file_picker:
  flutter_typeahead:
  google_fonts:
  mobkit_dashed_border: ^0.0.6
  flutter_blue: ^0.8.0
  flutter_zebra_sdk: ^0.0.4+1
  flutter_barcode_scanner:
#  zebrautility: ^0.0.41
#  zsdk: ^2.0.0+11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true